### ISSUE TITLE
Packager returned unexpected code 500

### ISSUE THREAD

**Issue by belohlavek** [exponentjs/exp#12]
Hello! This time I'm trying to build a standalone app on Linux (Lubuntu 15.04), after running `exp build:android` and following the instructions in the docs, I get the following error:
```
? Would you like to upload a keystore or have us generate one for you?
If you don't know what this means, let us handle it! :)
 false
[exp] Starting build process...
[exp] Publishing...
|[exp] Packager returned unexpected code 500
Error: Packager returned unexpected code 500
    at XDLError.Error (native)
    at new XDLError (/Users/Jesse/Exponent/newuniverse/universe/dev/xdl/gulp/src/XDLError.js:12:46)
    at _callee4$ (/Users/Jesse/Exponent/newuniverse/universe/dev/xdl/gulp/src/Project.js:83:11)
    at tryCatch (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (/usr/local/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
    at run (/usr/local/lib/node_modules/exp/node_modules/core-js/library/modules/es6.promise.js:87:22)
    at /usr/local/lib/node_modules/exp/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/exp/node_modules/core-js/library/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Any tips about what's going on? Thanks in advance!

**Comment by jesseruder** [comment]
Looks like your project isn't building. Was it working when you opened it on your phone?

**Comment by belohlavek** [comment]
Yep, just tested again from XDE and it's working!

**Comment by jesseruder** [comment]
Anything useful in `exp logs`?

**Comment by belohlavek** [comment]
Found something!

```
exp-serve/test:16a1deb4-0 (err): Error: 'node_modules/react-native/Libraries/CustomComponents/NavigationExperimental/assets/back-icon@1.5x.ios.png' could not be found, because 'node_modules/react-native/Libraries/CustomComponents/NavigationExperimental/assets' is not a subdirectory of any of the roots
```

Maybe something went wrong when I installed the dependencies?

**Comment by jesseruder** [comment]
Might be easier to join our slack to figure this out https://slack.exponentjs.com. you sure the same project is working in xde?

**Comment by belohlavek** [comment]
I * think * I'm sure. I'll triple check things anyways!
I'll close this issue since it's clearly my problem, and I'll join you guys on slack tomorrow (I can't today!)
Thanks for the help!

**Comment by enkeli** [comment]
Might come in handy for someone having this issue too: 
`react-native link`
on my project resolved the issue

**Comment by ide** [comment]
`react-native link` might accidentally fix this issue but it's not the right fix. It sounds like there could be an issue with the packager. I'd recommend clearing your node_modules and re-installing (if you use Yarn this step is much more likely to be reliable), run `watchman watch-del-all`, and restart the packager (click Restart in XDE for example).
