### ISSUE TITLE
exp start (and exp init) throws "SyntaxError: Unexpected token default"

### ISSUE THREAD

**Issue by krstffr** [exponentjs/exp#15]
Just installed the cli and tried to run `exp start` in a project which works fine on using the native Exponent XDE Mac app.

The error:

```
Warning: Problem in exp.json. Unexpected token default. See https://docs.getexponent.com/.
exp-serve/testing-exponent:fe3c3ab8-0 (err): [exp] SyntaxError: Unexpected token default
exp-serve/testing-exponent:fe3c3ab8-0 (err): Error: SyntaxError: Unexpected token default
exp-serve/testing-exponent:fe3c3ab8-0 (err):     at XDLError.Error (native)
exp-serve/testing-exponent:fe3c3ab8-0 (err):     at new XDLError (/Users/Jesse/Exponent/newuniverse/universe/dev/xdl/gulp/src/XDLError.js:12:46)
exp-serve/testing-exponent:fe3c3ab8-0 (err):     at _callee7$ (/Users/Jesse/Exponent/newuniverse/universe/dev/xdl/gulp/src/UrlUtils.js:85:13)
exp-serve/testing-exponent:fe3c3ab8-0 (err):     at tryCatch (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:62:40)
exp-serve/testing-exponent:fe3c3ab8-0 (err):     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:336:22)
exp-serve/testing-exponent:fe3c3ab8-0 (err):     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:95:21)
exp-serve/testing-exponent:fe3c3ab8-0 (err):     at step (/usr/local/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
exp-serve/testing-exponent:fe3c3ab8-0 (err):     at /usr/local/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
exp-serve/testing-exponent:fe3c3ab8-0 (err):     at Promise.F (/usr/local/lib/node_modules/exp/node_modules/core-js/library/modules/_export.js:35:28)
exp-serve/testing-exponent:fe3c3ab8-0 (err):     at /usr/local/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
exp-serve/testing-exponent:fe3c3ab8-0 (err):     at constructUrlAsync (/usr/local/lib/node_modules/exp/node_modules/xdl/build/UrlUtils.js:320:18)
exp-serve/testing-exponent:fe3c3ab8-0 (err):     at Object._callee$ (/Users/Jesse/Exponent/newuniverse/universe/dev/xdl/gulp/src/UrlUtils.js:18:10)
exp-serve/testing-exponent:fe3c3ab8-0 (err):     at tryCatch (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:62:40)
exp-serve/testing-exponent:fe3c3ab8-0 (err):     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:336:22)
exp-serve/testing-exponent:fe3c3ab8-0 (err):     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:95:21)
exp-serve/testing-exponent:fe3c3ab8-0 (err):     at step (/usr/local/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
```

There is no `default` key/word/value whatever in the exp.json, so I suspect the error is related to javascript exports? Maybe some node version mismatch (I'm using 6.8.0)?

**Comment by krstffr** [comment]
Oh, `exp init` throws the same error.

**Comment by ccheever** [comment]
Hi @krstffr -- What version of `exp` did you install? and how did you install it?

**Comment by harpsha** [comment]
@ccheever I'm facing the same error with exp v0.25.1

**Comment by cameronbarker** [comment]
👍  having same issue with v0.25.1

**Comment by jesseruder** [comment]
Sorry everyone, looking at this now.

**Comment by ide** [comment]
One of our transitive dependencies of `exp` broke. Can you try reinstalling `exp` with `npm uninstall -g exp && npm install -g exp`? That should pull down the newest, fixed dependency.

**Comment by cameronbarker** [comment]
@jesseruder @ide `exp start` is working for me after following the above directions.  Thanks guys

**Comment by ide** [comment]
@cameronbarker thanks for verifying! We'll close this out.
