### ISSUE TITLE
Blank project fails

### ISSUE THREAD

**Issue by jbaron** [exponentjs/exp#18]
When using "exp init" to create an new project and selecting the blank project template, there is an exception. The tabs project works fine.  exp version is 0.25.1 (latest npm version)

The stack trace is:

[exp] Downloading project files...
[exp] First argument must be an array
TypeError: First argument must be an array
    at module.exports (/usr/local/lib/node_modules/exp/node_modules/each-async/index.js:12:9)
    at Download.run (/usr/local/lib/node_modules/exp/node_modules/download/index.js:115:2)
    at eval (eval at promisify (/usr/local/lib/node_modules/exp/node_modules/instapromise/build/promisify.js:60:15), <anonymous>:12:18)
    at Download.eval (eval at promisify (/usr/local/lib/node_modules/exp/node_modules/instapromise/build/promisify.js:60:15), <anonymous>:10:12)
    at _callee3$ (/Users/Jesse/Exponent/newuniverse/universe/dev/xdl/gulp/src/Exp.js:136:75)
    at tryCatch (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/exp/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (/usr/local/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/exp/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at run (/usr/local/lib/node_modules/exp/node_modules/core-js/library/modules/es6.promise.js:87:22)
    at /usr/local/lib/node_modules/exp/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/exp/node_modules/core-js/library/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by jbaron** [comment]
The new version of exponent seems to have fixed this, thanks.
